### ISSUE TITLE
problem on build

### ISSUE THREAD

**Issue by Vulneraria** [felixb/eucookieconsent#1]
i get this error:

Error:(33, 13) Failed to resolve: de.ub0r.android:eucookieconsent:+

let me know.

thank you

**Comment by felixb** [comment]
it's `de.ub0r.android.eucookieconsent:library:+@aar`.

**Comment by Vulneraria** [comment]
I have used that, is the android studio message that remove @aar

Vulne.
my Apps! https://play.google.com/store/search?q=pub:Vulneraria

2015-09-23 18:59 GMT+02:00 Felix Bechstein notifications@github.com:
